### ISSUE TITLE
practice issue

### ISSUE THREAD

**Issue by camilavargasp** [ecodatascience/ecodatascience.github.io#4]
Hye @oharac please checkout this

**Comment by oharac** [comment]
hey @camilavargasp great issue, two thumbs up 👍 👍

**Comment by camilavargasp** [comment]
This is the logo on out landing page, what do you think?
![image](https://github.com/ecodatascience/ecodatascience.github.io/assets/35848897/0cc1ab54-b886-4d48-8500-4901a5ba7c9c)

**Comment by camilavargasp** [comment]
Practice issue for GH for project management workshop
